<a href="https://colab.research.google.com/github/dednomerios/ML_2024_Aliyari/blob/main/HW1_emtiazi/HW1_emtiazi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Soal 5

In [45]:
import numpy as np
import random
number_of_iterations = 10
for i in range(number_of_iterations):
  random_vars = [random.randint(0,5) for _ in range(6)]

  a, b, c, d, e, f = random_vars

  upper_triangular_matrix = np.array([
    [a, b, c],
    [0, d, e],
    [0, 0, f]
  ])

  print(f'the matrix is: \n {upper_triangular_matrix}')
  is_singular = np.linalg.det(upper_triangular_matrix) == 0

  print(f"Is the matrix singular? {'Yes' if is_singular else 'No'}")


the matrix is: 
 [[3 4 2]
 [0 4 2]
 [0 0 1]]
Is the matrix singular? No
the matrix is: 
 [[1 0 4]
 [0 0 5]
 [0 0 1]]
Is the matrix singular? Yes
the matrix is: 
 [[1 2 2]
 [0 0 0]
 [0 0 5]]
Is the matrix singular? Yes
the matrix is: 
 [[2 0 3]
 [0 3 2]
 [0 0 2]]
Is the matrix singular? No
the matrix is: 
 [[1 5 0]
 [0 2 5]
 [0 0 5]]
Is the matrix singular? No
the matrix is: 
 [[1 0 1]
 [0 0 4]
 [0 0 1]]
Is the matrix singular? Yes
the matrix is: 
 [[5 1 2]
 [0 3 4]
 [0 0 5]]
Is the matrix singular? No
the matrix is: 
 [[0 3 3]
 [0 3 5]
 [0 0 4]]
Is the matrix singular? Yes
the matrix is: 
 [[2 0 5]
 [0 5 4]
 [0 0 4]]
Is the matrix singular? No
the matrix is: 
 [[2 3 5]
 [0 2 5]
 [0 0 5]]
Is the matrix singular? No


# Soal 6

In [44]:
import numpy as np
import timeit


m, n = 20, 10
A = np.random.rand(m, n)
k = np.random.rand(n)

def nested_mul():
  p = np.zeros(m)
  for i in range(n):
    p += A[:, i] * k[i]
  return p
def vectorized_mul():
  return np.matmul(A,k)

nested_reult = nested_mul()
vectorized_reult = vectorized_mul()

np.allclose(nested_reult, vectorized_reult)
print(f"is they close? {'Yes' if np.allclose else 'No'}")

nested_mul_time = timeit.timeit(nested_mul, number = 10000)
vectorized_mul_time = timeit.timeit(vectorized_mul, number = 10000)

print(f" Run time nested: {nested_mul_time:.7f} seconds")
print(f" Run time vectorized: {vectorized_mul_time:.7f} seconds")

is they close? Yes
 Run time nested: 0.1850998 seconds
 Run time vectorized: 0.0122411 seconds
